query {
    users {
        data {
            id
            name
            email
            posts{
                id
                content
                created_at
            }
        }
    }
}